Bootstrap the manager process
replicatedhq/embedded-cluster pull request #1525
Opened 2024-11-19 21:59 UTC by marccampbell

2024-11-19 22:20 UTC, emosbaugh requested changes

2024-11-19 22:20 UTC, emosbaugh commented on cmd/manager/status.go
> +	"io/ioutil"
ioutil has been deprecated

2024-11-19 22:20 UTC, emosbaugh commented on pkg/socket/server.go
> +	tmpDir := os.TempDir()
shouldnt you use /var/run for this?

2024-11-21 18:26 UTC, emosbaugh requested changes

2024-11-21 18:26 UTC, emosbaugh commented on pkg/websocket/server.go
> +			logrus.Errorf("Failed to send pong message to server: %v", err)
Why log and not return the error here? Im not saying it is correct. im just assuming the client will not receive the error so im wondering what is the desired behavior here.

2024-11-21 18:38 UTC, sgalsaleh commented on pkg/websocket/server.go
> +			return errors.Wrap(err, "send ping message")
this error typically happens when the connection is closed. when this returns, the manager will try to reconnect to kots again.

2024-11-22 23:13 UTC, emosbaugh requested changes

2024-11-22 23:13 UTC, emosbaugh commented on cmd/manager/status.go
> +			return getServerStatus(ctx)
```suggestion
			return printServerStatus(ctx)
```

2024-11-22 23:13 UTC, emosbaugh commented on cmd/manager/status.go
> +func getServerStatus(ctx context.Context) error {
```suggestion
func printServerStatus(ctx context.Context) error {
```

2024-11-26 20:29 UTC, emosbaugh approved these changes

2024-11-26 22:51 UTC, emosbaugh approved these changes

2024-11-26 22:52 UTC, merged